services:
  transformer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Mount data directories from host
      - ./data/raw:/app/data/raw
      - ./data/processed:/app/data/processed
      # Mount the models_docker directory for Docker-trained models
      - ./models_docker:/app/models
      # The following directories will be created fresh in the container
      # and persist between container runs
      - transformer_logs:/app/logs
      - transformer_reports:/app/reports
    # Enable interactive mode
    stdin_open: true
    tty: true
    # Set working directory
    working_dir: /app
    # Default command (can be overridden)
    command: bash
    # Add memory limits - increase as needed
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 8G
          devices:
            - driver: gpu
              capabilities: [gpu, utility, compute, graphics]
    # Enable GPU access for DirectML
    environment:
      - DIRECTML_GPU_ENABLE=1
      - TF_FORCE_GPU_ALLOW_GROWTH=true

# Define named volumes to persist data between container runs
volumes:
  transformer_logs:
  transformer_reports: 