# Data paths
train_data_path: "data/raw/Monthly-train.csv"
test_data_path: "data/raw/Monthly-test.csv"
processed_data_path: "data/processed"

# Tourism data paths
tourism_train_data_path: "data/processed/tourism_monthly_dataset.csv"
tourism_test_data_path: "data/processed/tourism_monthly_test.csv"

# Sequence parameters
extension: 61  # Sequence length
input_seq_len: 60  # Input sequence length for tourism data
output_seq_len: 24  # Output sequence length (forecast horizon) for tourism data
batch_size: 16  # Reduced from 32 to help with memory usage
random_seed: 42

# Data split ratios (only applied to training data)
validation_split: 0.2  # Percentage of training data to use for validation 

# Detrending configuration for training
detrending:
  enabled: false  # Whether to detrend series before creating subsamples
  min_points_stl: 12  # Minimum points required for STL decomposition
  min_points_linear: 5  # Minimum points required for linear regression
  force_linear: false  # Force using linear detrending even if STL is possible 

# Data type configuration
dtype:
  precision: "float16"  # Changed to float32 for tourism dataset for better precision 