# Inference Configuration

# Whether to apply detrending during inference
# If true, the forecast generator will perform trend decomposition and recomposition
# If false, no detrending/retrending will be applied
apply_detrending: true

# Whether to only remove positive trends
# If true, negative trends will be preserved (not removed)
# If false, all trends will be removed regardless of direction
remove_only_positive_trends: true

# Whether to disable linear detrending completely
# If true, linear detrending will be skipped, even when STL isn't possible
# If false, linear detrending will be used as a fallback when STL isn't possible
disable_linear_detrending: false

# Minimum points required for different detrending methods
min_points_stl: 40 # was 12 before
min_points_linear: 5

# Confidence interval settings
default_low_bound_conf: 30
default_high_bound_conf: 70

# Number of samples for uncertainty estimation
default_num_samples: 1000 